title: å¤šè§†è§‰èåˆä¸‰ç»´é‡å»ºå¹³å°æ­å»º | æ–‡æ¡£
description: ç»¼åˆè®¾è®¡é¡¹ç›®æ–‡æ¡£
theme: just-the-docs

url: https://MV3DR-team.github.io/MV3DR-Docs

aux_links:
  "Github é¡¹ç›®ä»£ç ":
    - "https://github.com/MV3DR-team/Multi-View-3D-Reconstruction"

aux_links_new_tab: true

callouts:
  warning:
    title: â—è­¦å‘Š
    color: red
  note:
    title: ğŸ“è¯´æ˜
    color: green
  important:
    titile: â•é‡è¦
    color: purple

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "åœ¨ Github ä¸Šç¼–è¾‘æ­¤é¡µ"
gh_edit_repository: "https://github.com/MV3DR-team/MV3DR-Docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree"